apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-request-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespace-request-operator
  template:
    metadata:
      labels:
        name: namespace-request-operator
    spec:
      serviceAccountName: namespace-request-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "docker-registry.default.svc:5000/namespace-request/namespace-request-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "docker-registry.default.svc:5000/namespace-request/namespace-request-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespace-request-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
