kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-request-operator
subjects:
- kind: ServiceAccount
  name: namespace-request-operator
  namespace: namespace-request
roleRef:
  kind: ClusterRole
  name: namespace-request-operator
  apiGroup: rbac.authorization.k8s.io
